services:
  web:
    build:
     context: ./
     dockerfile: Dockerfile
    image: Flask
    # 添加host解决raw.githubusercontent.com:443污染
    # curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to raw.githubusercontent.com:443
    extra_hosts:
      - "raw.githubusercontent.com:199.232.68.133"
